services:
  web:
    image: spliceai-lookup_docker:${VERSION}
    build: .
    ports:
      - "8001:8080"
    restart: always
    volumes:
      - /mnt/data1/db/spliceai/references_files:/Users/jocotton/Desktop/references_files
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
