name: Upload Datasets

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload datasets
      uses: actions/upload-artifact@v2
      with:
        name: my-dataset
        path: /Users/jocotton/Desktop/references_files
